### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by faddat** [JackalLabs/canine-chain#74]
Ok, so, first off, I want to express gratitude to the chain and validators for making the decision to halt.  

And to Jim Yang from Osmosis for... heaping the pressure on validators. 

Now we can improve the chain, safely. 

I couldn't say any of this while the chain was running, and I was in fact guarding my words a great deal.

Here's a plan-- 

- [x] We are going to start from v1.1.1, not main, because v1.1.1 is what validators should be running
- [x] We are going to make a branch called v1.1.1-secure
- [x] Merge #76 
- [x] #84
- [x] #86
  - [x] audit
  - [x] remove dependency on storagekeeper 
- [x] we are going to eject ignite cli because it interferes with various security processes (ignite was mainly used for the very pretty openapi server)
  - [x] restructure cmd (wasn't needed)
  - [x] add app/params/* (alreaady there)
  - [x] make changes to app.go to replace `cosmoscmd` (all good)
  - [x] ensure that every usage of `cosmoscmd` `ignite` and related libraries has been eliminated from `canine-chain` (all good)
  - [x] remove testutil/* 
- [x] we are going to remove every module that contains unneeded code from the branch `v1.1.1-secure`
  - [X] REMOVE FROM APP.GO
    - [X] storage
    - [X] dsig
    - [X] notifications
    - [X] filetreekeeper
  - [x] UPGRADE HANDLER THAT SETS STOREKEY TO NIL, REMOVING THE MODULE
    - [x] storage
    - [x] dsig
    - [x] notifications
    - [x] filetreekeeper
- [x] we are going to use golangci-lint v1.50.1 with go 1.19 using the configuration from the branch golangci in notional-labs/canine-chain
  - [x] Jackal passes all linters
- [x] remove unnecessary .proto files 
- [x] we are going to use cosmos-sdk v0.45.10
- [x] we are going to use ibc-go v3.3.1
- [x] we will likely need to introduce new tests, since all current tests depend on ignite wrappers, though some may be applicable
  - [x] jklmint
  - [x] rns
- [x] #94

## Damage Assessment

- [x] make a hard determination if validator filesystems were put at risk
  - [x] determine level of interplay between `rando http server` and filetree and storage
RESULT: I **think** that they weren't, and we should refactor these modules before putting them back into play.

- [x] determine if user data or funds were put at risk and to what degree
RESULT: they weren't except in an adversarial economic attack scenario where an adversary attempts to drain liquidity from exchanges where jkl is listed by halting JKL.

- [ ] look at ibc transactions between jackal and osmosis

- [x] look at history from secret network
RESULT: 
* mixed community feedback, mostly airdrop related, totally normal. 
* Team says they chose to build their own solution rather than use secret.  This is fine too, that's their choice. 

## Auditors

To my knowledge there were auditors from entersoft and certik on this repository.  They've hard failed full stop and no one in cosmos should engage again.

* ~~certik~~
* ~~entersoft~~

Certik and entersoft are encouraged to contact me, Jacob Gadikian, here:

https://twitter.com/gadikian

but not elsewhere please.

## Addendum

As a gift for doing this work, CitadelOne's CEO had a little message for me, complete with screenshots of the private validators' discord server.  It wasn't a very nice message at all.

https://twitter.com/gadikian/status/1587332554675609600

**Comment by effofxprime** [comment]
How can I help?

**Comment by faddat** [comment]
Possibly the upgrade handler?

Chain currently has hard dependencies on chernobyl grade code.

**Comment by bjaanes** [comment]
@faddat wanting to help here, but need to be able to communicate and coordinate directly with you. Please take a look at Discord and let me know where I can help.

**Comment by faddat** [comment]
@bjaanes there were a lot of surprises here, if I were you I'd audit the mint module.

**Comment by bjaanes** [comment]
Looking through it now @faddat

**Comment by effofxprime** [comment]
> Possibly the upgrade handler?
> 
> Chain currently has hard dependencies on chernobyl grade code.
> 
> I forget where, but somewhere you should be able to find an example for removing a module. Basically though you'd set the storekey for the module to nil.

So after looking and comparing against how other chains have their upgradehandler.go set, I couldn't find one for Jackal.  when I search the repo for "upgrade", no upgrade handler is present.

I am most definitely interested in learning how to get it created, might need some hand holding.  (which doesn't help the situation I know).  I had looked at how this is done on other chains and default from cosmos SDK repo, but stopped there because I wasn't sure in exactly what I need to include.

**Comment by faddat** [comment]
afaik you set the storekey to nil, and I would recommend that you tweet at cosmos-sdk while tagging me, seems to work ok for me :)

**Comment by Reecepbcups** [comment]
@effofxprime yea you have to create the upgrade handler functions & version logic in app.go first.
I think the solution in PR 99 is correct, but is also my first time doing an Upgrade Handler. Seems to just be

- check if there is an upgrade, if there is panic at height
- find what the new upgrade version is
- run the Handler for that version
- delete the keys from the versionMap (we can't set StoreKey = nil since the store keys were already removed by deleting the module afaik)

**Comment by faddat** [comment]
https://twitter.com/gadikian/status/1588026507750146049

Project team members can reach me on Twitter, and I should note that I never had the opportunity to complete an audit, and that the only thing I can say for sure is that the state of the chain code is now far far better than it was previously.

It is not possible to pursue this work with the conditions created by the CEO of CitadelDAO, Anton.

Here's a brief summary, that I'm cross posting from the osmosis discord server.  

I would respectfully request that it remain here as Notional Labs has suffered deeply due to the actions of CitadelDAO and I wish to memorialize them.

Hey I just wanted to announce in here, that notional is leaving Jackal. Working on that chain has been the most unpleasant experience that I personally have ever had working with another team.  I imagine there's going to be a lot of noise around this and basically just want to let the osmosis community know that while clearly notional and jackal are not in any way compatible, we wish them the best. 

Our team has continued to contribute software to their chain in the hopes of getting it back up, and we will remain in their discord server until either it is back up or asked to leave. 

To get an idea of the scope and depth of our contributions there, here is the commit log for that chain:

https://github.com/JackalLabs/canine-chain/commits/master

Due to the activities of the CEO of CitadelDAO we have lost a ton of time working on the chain, and on other initiatives.  The screenshot that he took was both out of context and used with malice.  I wish to advise the community to exercise caution with them as that specific action took time out of a sensitive situation and put us on the defensive.  When the Jackal team failed to correct the non factual statements made by Citadel's CEO, and failed to provide information about the audit they said they'd had, we decided that it was time to leave. 

Concerning audits, please note that there were three accounts with auditor like names on their GitHub that disappeared during the course of our work.  One was certik, the other was entersoft.  The jackal team has told us that they'd been manually testing the code with their auditor, entersoft, but frankly, this doesn't add up to me.  They also said that they'd added a certik team member to their repository to get a quote, but that also doesn't add up to me.  I've asked their team to provide information like an invoice concerning an audit and they've refused, stating that the audit they had on their public blockchain was private information.  Please know that is not the typical standard, and that any decent auditor would be doing stuff like:

https://twitter.com/gadikian/status/1586800307987546112

And that if Jackal had been audited at all, which the Jackal Labs team refuses to provide evidence of, then the auditor completely failed.  

Here's the tracking issue for what notional did with Jackal:

https://github.com/JackalLabs/canine-chain/issues/74

Apologetic to our delegators on jackal about this.  Since we intend to leave, when the chain does begin to run again, we will remove our self bonded stake and you will not be slashed for our downtime.

https://twitter.com/gadikian/status/1587771444230262784?t=L0xmPQ9U0Xc2jimIsbpO2A&s=19

**In the end**, our decision to leave was based on the fact that due to the activities of <@109306243775991808> (taking screenshots in the validator chat, weather that's right or wrong is immaterial here) and his CEO Anton at CitadelDAO, notional stood to lose far more than we could ever gain from being involved with jackal because their team refused to correct non factual statements made by Anton, CEO of CitadelDAO, founded by:

https://www.linkedin.com/in/alex-falko-a3b79289/

**Validators who feel that the Jackal chain was halted in error, should simply restart their nodes with the current v1.1.1 binary.**

**Comment by faddat** [comment]
I also wish to say that I sincerely wish Jackal the very best in their endeavor.  While I disagree with their strategic decision to leave me hanging with respect to SwissCheeseDAO, I believe that the team is well intentioned, but perhaps inexperienced with Cosmos.

I truly wished to assist them -- even more in depth than our team did here -- and build a relationship lasting years, but that is just untenable given the situation with Anton, CEO of CitadelDAO.

![Screenshot_20221101-140355](https://user-images.githubusercontent.com/7142025/199651104-312a3d1a-e36d-477d-a0cf-f835018531b0.png)
