### ISSUE TITLE
new tests should follow the style of ibc-go, wasmd, and cosmos-sdk

### ISSUE THREAD

**Issue by faddat** [JackalLabs/canine-chain#94]
Interestingly, it seems to work to use the sdk 47 style tests, including depinject. 

I am not certain why/how this works, but this is a feather in the cap of the sdk team.  When writing these tests, please ensure to be careful, as I cannot say for sure that sdk 47 test style and sdk 45 test style will work all the time. 

But I do understand that greater compatibility has been a goal of the sdk team.

**Comment by faddat** [comment]
--- FAIL: TestMsgAcceptBid_ValidateBasic (0.00s)
    --- FAIL: TestMsgAcceptBid_ValidateBasic/valid_address (0.00s)
        message_accept_bid_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_accept_bid_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgAcceptBid).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_accept_bid.go:44
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgAcceptBid_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_accept_bid_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgAcceptBid_ValidateBasic/valid_address
--- FAIL: TestMsgAddRecord_ValidateBasic (0.00s)
    --- FAIL: TestMsgAddRecord_ValidateBasic/valid_address (0.00s)
        message_add_record_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_add_record_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgAddRecord).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_add_record.go:46
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgAddRecord_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_add_record_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgAddRecord_ValidateBasic/valid_address
--- FAIL: TestMsgDelRecord_ValidateBasic (0.00s)
    --- FAIL: TestMsgDelRecord_ValidateBasic/valid_address (0.00s)
        message_addel_redcord_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_addel_redcord_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgDelRecord).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_addel_redcord.go:43
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgDelRecord_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_addel_redcord_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgDelRecord_ValidateBasic/valid_address
--- FAIL: TestMsgBid_ValidateBasic (0.00s)
    --- FAIL: TestMsgBid_ValidateBasic/valid_address (0.00s)
        message_bid_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_bid_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgBid).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_bid.go:44
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgBid_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_bid_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgBid_ValidateBasic/valid_address
--- FAIL: TestMsgBuy_ValidateBasic (0.00s)
    --- FAIL: TestMsgBuy_ValidateBasic/valid_address (0.00s)
        message_buy_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_buy_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgBuy).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_buy.go:43
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgBuy_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_buy_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgBuy_ValidateBasic/valid_address
--- FAIL: TestMsgCancelBid_ValidateBasic (0.00s)
    --- FAIL: TestMsgCancelBid_ValidateBasic/valid_address (0.00s)
        message_cancel_bid_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_cancel_bid_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgCancelBid).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_cancel_bid.go:43
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgCancelBid_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_cancel_bid_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgCancelBid_ValidateBasic/valid_address
--- FAIL: TestMsgDelist_ValidateBasic (0.00s)
    --- FAIL: TestMsgDelist_ValidateBasic/valid_address (0.00s)
        message_delist_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_delist_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgDelist).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_delist.go:43
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgDelist_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_delist_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgDelist_ValidateBasic/valid_address
--- FAIL: TestMsgInit_ValidateBasic (0.00s)
    --- FAIL: TestMsgInit_ValidateBasic/valid_address (0.00s)
        message_init_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_init_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgInit).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_init.go:42
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgInit_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_init_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgInit_ValidateBasic/valid_address
--- FAIL: TestMsgList_ValidateBasic (0.00s)
    --- FAIL: TestMsgList_ValidateBasic/valid_address (0.00s)
        message_list_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_list_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgList).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_list.go:44
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgList_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_list_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgList_ValidateBasic/valid_address
--- FAIL: TestMsgRegister_ValidateBasic (0.00s)
    --- FAIL: TestMsgRegister_ValidateBasic/valid_address (0.00s)
        message_register_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_register_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgRegister).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_register.go:45
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgRegister_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_register_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgRegister_ValidateBasic/valid_address
--- FAIL: TestMsgTransfer_ValidateBasic (0.00s)
    --- FAIL: TestMsgTransfer_ValidateBasic/valid_address (0.00s)
        message_transfer_test.go:39: 
            	Error Trace:	/home/runner/work/canine-chain/canine-chain/x/rns/types/message_transfer_test.go:39
            	Error:      	Received unexpected error:
            	            	
            	            	github.com/jackalLabs/canine-chain/x/rns/types.(*MsgTransfer).ValidateBasic
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_transfer.go:44
            	            	github.com/jackalLabs/canine-chain/x/rns/types.TestMsgTransfer_ValidateBasic.func1
            	            		/home/runner/work/canine-chain/canine-chain/x/rns/types/message_transfer_test.go:34
            	            	invalid creator address (empty address string is not allowed): invalid address
            	Test:       	TestMsgTransfer_ValidateBasic/valid_address

**Comment by TheMarstonConnell** [comment]
Fixed mentioned errors in #96 still going to build better tests
